version: '3'
services:
  csgbackend:
    build: ./backend/docker
    ports:
      - "5000:5000"
    volumes:
      - ./backend/app:/app
  csgfrontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "8089:80"
    depends_on:
      - csgbackend

networks:
  default:
    external:
      name: nginxproxymanager_default